
set MATLAB=C:\Program Files\MATLAB\R2022b

"C:\IPG\carmaker\win64-13.0.1\bin\cmmake" -f SwitchMobility_ACC.mk  EXT_MODE=0 EXTMODE_STATIC_ALLOC=0 TMW_EXTMODE_TESTING=0 EXTMODE_STATIC_ALLOC_SIZE=1000000 EXTMODE_TRANSPORT=0 MAT_FILE=0 CM_VEHICLECLASS="Truck" COMBINE_OUTPUT_UPDATE_FCNS=1 INCLUDE_MDL_TERMINATE_FCN=1 MULTI_INSTANCE_CODE=1 OPTS="-DRT_MALLOC -DTID01EQ=0"
